#ifndef COMMAND_LS_H
#define COMMAND_LS_H

#define CLEAR_STRING "clear"
#define CLS_STRING "cls"
#define LIST_STRING "list"
#define SEQLIST_STRING "seqlist"
#define VER_STRING "ver"
#define SHELLINFO_STRING "shellinfo"
#define OSFETCH_STRING "osfetch"
#define SHUTDOWN_STRING "shutdown"
#define REBOOT_STRING "reboot"
#define TIME_STRING "time"
#define VERSION_STRING "version"
#define ECHO_STRING "echo "
#define CPUINFO_STRING "cpuinfo"
#define HELP_STRING "help"
#define DISKINFO_STRING "diskinfo"
#define SYSINFO_STRING "sysinfo"
#define DIR_STRING "dir"
#define LS_STRING "ls"
#define COPY_STRING "copy"
#define REN_STRING "ren"
#define DEL_STRING "del"
#define CAT_STRING "cat"
#define SIZE_STRING "size"
#define RUNAPP_STRING "runapp "
#define LISTAPP_STRING "listapp"

/*
U: Upper case
*/

#define U_CLEAR_STRING "CLEAR"
#define U_CLS_STRING "CLS"
#define U_LIST_STRING "LIST"
#define U_SEQLIST_STRING "SEQLIST"
#define U_VER_STRING "VER"
#define U_SHELLINFO_STRING "SHELLINFO"
#define U_OSFETCH_STRING "OSFETCH"
#define U_SHUTDOWN_STRING "SHUTDOWN"
#define U_REBOOT_STRING "REBOOT"
#define U_TIME_STRING "TIME"
#define U_VERSION_STRING "VERSION"
#define U_ECHO_STRING "ECHO "
#define U_CPUINFO_STRING "CPUINFO"
#define U_HELP_STRING "HELP"
#define U_DISKINFO_STRING "DISKINFO"
#define U_SYSINFO_STRING "SYSINFO"
#define U_DIR_STRING "DIR"
#define U_LS_STRING "LS"
#define U_COPY_STRING "COPY"
#define U_REN_STRING "REN"
#define U_DEL_STRING "DEL"
#define U_CAT_STRING "CAT"
#define U_SIZE_STRING "SIZE"
#define U_RUNAPP_STRING "RUNAPP "
#define U_LISTAPP_STRING "LISTAPP"

#endif